### ISSUE TITLE
RealFuels install error

### ISSUE THREAD

**Issue by Andy81le** [KSP-CKAN/CKAN-meta#677] opened 2015-07-05 10:36 UTC
GameData/SolverEngines/SolverEngines.version
Installing Mod : ModuleAnimateEmissive v1.5
Owning Mod     : SolverEngines
CKAN Version   : v1.10.0-0-gb447380 (beta)

Your GameData has been returned to its original state.

Getting this error when installing RealFuels.

**Comment by dbent** [comment] 2015-07-05 15:31
Closing as duplicate of #676

**Closed by dbent** 2015-07-05 15:31 UTC
