### ISSUE TITLE
CustomBiomes and UniversalStorage-KAS bug

### ISSUE THREAD

**Issue by wilfrem** [KSP-CKAN/CKAN-meta#232] opened 2015-01-04 15:41 UTC
Hi, I found two bug after #229 . I install Realism Overhaul again without RealPlume. so found two bug.

first

```
About to remove:

Done!

About to install...

 * RealismOverhaul v7.0.4 (cached)
 * AJE 1.7a (cached)
 * FerramAerospaceResearch v0.14.6 (cached)
 * ModuleManager 2.5.6 (cached)
 * CrossFeedEnabler v3.2 (cached)
 * KerbalJointReinforcement v3.0.1 (cached)
 * ModuleRCSFX v3.4 (cached)
 * RealFuels rf-v8.3 (cached)
 * RealSolarSystem v8.5 (cached)
 * DDSLoader 1.8.0.0 (cached)
 * ActiveTextureManagement 1.0_x86 (cached)
 * ConnectedLivingSpace 1.1.0.0 (cached)
 * DeadlyReentry v6.4.0 (cached)
 * KSP-AVC 1.1.5.0 (cached)
 * ProceduralDynamics v0.9.3 (cached)
 * ProceduralFairings v3.11 (cached)
 * ProceduralParts v0.9.21 (cached)
 * RealChute 1.2.6.3 (cached)
 * RemoteTech v1.5.2 (cached)
 * TextureReplacer 2.1.2 (cached)
 * Toolbar 1.7.8 (cached)
 * TweakScale v1.50 (cached)
 * CustomBiomes-Data-RSS v8.5 (cached)
 * KAS 0.4.10 (cached)
 * SCANsat 8.1 (cached)
 * RemoteTech-Config-RSS 0.0 (cached)
 * RSSTexturesDDS8192 1.0 (cached)
 * CustomBiomes v1.7.2 (cached)

Module "Realism Overhaul" successfully installed
Module "Advanced Jet Engine (AJE)" successfully installed
Module "Ferram Aerospace Research" successfully installed
Module "Module Manager" successfully installed
Module "Crossfeed Enabler" successfully installed
Module "Kerbal Joint Reinforcement" successfully installed
Module "ModuleRCSFX" successfully installed
Module "Real Fuels" successfully installed
Module "Real Solar System" successfully installed
Module "DDSLoader" successfully installed
Module "Active Texture Management" successfully installed
Module "Connected Living Space" successfully installed
Module "Deadly Reentry Continued" successfully installed
Module "KSP AVC" successfully installed
Module "Procedural Wings" successfully installed
Module "Procedural Fairings" successfully installed
Module "Procedural Parts" successfully installed
Module "RealChute Parachute Systems" successfully installed
Module "RemoteTech" successfully installed
Module "TextureReplacer" successfully installed
Module "Toolbar" successfully installed
Module "TweakScale" successfully installed
Module "Custom Biomes (Real Solar System data)" successfully installed
Module "Kerbal Attachment System" successfully installed
Module "SCANsat" successfully installed
Module "RemoteTech RSS Configuration" successfully installed
Module "Real Solar System Textures DDS - 8192 x 4096" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/CustomBiomes/biome.png
Installing Mod : CustomBiomes v1.7.2
Owning Mod     : CustomBiomes-Data-RSS
CKAN Version   : v1.5.3-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!
```

second
```
About to remove:

Done!

About to install...

 * RealFuels rf-v8.3 (cached)
 * RealismOverhaul v7.0.4 (cached)
 * DMagicOrbitalScience 0.9.1
 * NearFutureConstruction 0.4.0
 * NearFutureSolar 0.4.0
 * UniversalStorage 1.0.90.1
 * UniversalStorage-KAS 1.0.0
 * Regolith 0.1.2
 * CommunityResourcePack 0.3.2

Downloading "https://kerbalstuff.com/mod/5/DMagic Orbital Science/download/0.9.1"
Downloading "https://kerbalstuff.com/mod/348/Near Future Construction/download/0.4.0"
Downloading "https://kerbalstuff.com/mod/346/Near Future Solar/download/0.4.0"
Downloading "https://kerbalstuff.com/mod/250/Universal Storage/download/1.0.90.1"
Downloading "https://kerbalstuff.com/mod/365/Universal Storage [KAS PACK]/download/1.0.0"
Downloading "https://github.com/BobPalmer/Regolith/releases/download/0.1.2/Regolith_0.1.2.zip"
Downloading "https://github.com/BobPalmer/CommunityResourcePack/releases/download/0.3.2/CRP_0.3.2.zip"
Module "Real Fuels" successfully installed
Module "Realism Overhaul" successfully installed
Module "DMagic Orbital Science" successfully installed
Module "Near Future Construction" successfully installed
Module "Near Future Solar" successfully installed
Module "Universal Storage" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.3-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

```

**Comment by AlexanderDzhoganov** [comment] 2015-01-05 14:28
First bug has been fixed in https://github.com/KSP-CKAN/CKAN/releases/tag/v1.5.4, the second one is not a bug as UniveralStorage-KAS has been deprecated.

**Closed by AlexanderDzhoganov** 2015-01-05 14:28 UTC
