### ISSUE TITLE
InfernalRobotics 0.21.2

### ISSUE THREAD

**Issue by sergioberg** [KSP-CKAN/CKAN-meta#466] opened 2015-05-08 09:54 UTC
https://github.com/KSP-CKAN/CKAN-meta/tree/master/InfernalRobotics
0.21.2 is absent in CKAN app. Only 0.21. Something wrong.

**Comment by sergioberg** [comment] 2015-05-08 10:34
May be CKAN thinks: "v0.21" > "0.21.2"

**Comment by BlackSoldierB** [comment] 2015-05-09 13:58
Duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/133?

**Closed** 2015-05-12 19:16 UTC
