### ISSUE TITLE
401 error

### ISSUE THREAD

**Issue by JebJebKerman** [KSP-CKAN/CKAN-meta#386] opened 2015-04-26 12:58 UTC
Whenever I try to open CKAN I'm shown a 401 error and cannot refresh or download mods

**Comment by Dazpoet** [comment] 2015-04-26 14:34
Duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/113 which also has a functional workaround, check there and I'll close this one due to duplication.

**Closed by Dazpoet** 2015-04-26 14:34 UTC
