### ISSUE TITLE
Error installing using latest CKAN

### ISSUE THREAD

**Issue by ebigunso** [KSP-CKAN/CKAN-meta#680] opened 2015-07-05 15:49 UTC
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/SolverEngines/SolverEngines.version
Installing Mod : ModuleAnimateEmissive v1.5
Owning Mod     : SolverEngines
CKAN Version   : v1.10.0-0-gb447380 (beta)

This is what I got when I tried installing using the latest CKAN. Came here as written in the error log.

**Comment by plague006** [comment] 2015-07-05 17:31
Same as #676. Fix implemented in KSP-CKAN/NetKAN#1835.

**Comment by dbent** [comment] 2015-07-05 18:36
Closing as duplicate of #676.

**Closed by dbent** 2015-07-05 18:36 UTC
