### ISSUE TITLE
firespiter install bug.

### ISSUE THREAD

**Issue by Lazersgm** [KSP-CKAN/CKAN-meta#494] opened 2015-05-16 11:32 UTC
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/Firespitter/Resources/Firespitter.cfg
Installing Mod : KerbalAircraftExpansion v2.5
Owning Mod     : Firespitter
CKAN Version   : v1.6.16-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by dbent** [comment] 2015-05-16 14:33
Looks like a dupe of #472

**Comment by plague006** [comment] 2015-05-22 05:14
With KSP-CKAN/NetKAN#1264 complete it would be nice to know if this issue persists.

**Comment by Lazersgm** [comment] 2015-05-22 10:31
seems to have been fixed for me. thanks for the great program and hard work :)

**Closed** 2015-05-22 10:34 UTC
