### ISSUE TITLE
000_toolbar download not working.

### ISSUE THREAD

**Issue by lahtis** [KSP-CKAN/CKAN-meta#905] opened 2015-12-22 16:14 UTC
Try download 1.7.10 version. it say 000_Toolbar not found. But when you go in the browser same address toolbar found.

**Comment by Olympic1** [comment] 2015-12-22 18:12
Duplicate of https://github.com/KSP-CKAN/CKAN/issues/1544

**Closed by Olympic1** 2015-12-22 18:12 UTC
