### ISSUE TITLE
Toolbar 1.7.8 installed by CKAN is incompatible with 1.0.0

### ISSUE THREAD

**Issue by ErikEvenson** [KSP-CKAN/CKAN-meta#393] opened 2015-04-27 23:07 UTC
See https://github.com/blizzy78/ksp_toolbar/issues/33

**Comment by Dazpoet** [comment] 2015-04-27 23:22
Is it acctually not working or is KSP-AVC just reporting it's not compatible because the .version file isn't updated?

**Comment by ErikEvenson** [comment] 2015-04-27 23:49
I don't think it is working.  No toolbar appears.

**Comment by Dazpoet** [comment] 2015-04-28 20:54
Was this on a clean install? The toolbar thread seems to more and more convene on the conclucsion that this mod does work in 1.0 on a clean install.

**Comment by ErikEvenson** [comment] 2015-04-29 00:28
It was/is a clean install on OS X via Steam.  Mod was installed by CKAN.  Not sure what to say.

**Comment by Dazpoet** [comment] 2015-04-29 00:40
I had some people on irc try and it worked for them, looking at the thread it seems not all users get it working but I don't know why.

I won't remove 1.0 support from CKAN seeing as it does appear to work for some users but I'll try to have some time to install it on my own mac tomorrow and see if I can reproduce the issue.

**Comment by Dazpoet** [comment] 2015-05-03 23:41
1.7.9 seems to have resolved all issues, closing this

**Closed by Dazpoet** 2015-05-03 23:41 UTC
